local autoloot = select(2,...)

autoloot.german = {}

	autoloot.german[1] = "|cFFFF0000 Deaktiviert |r"
	autoloot.german[2] = "|cFF00FF00 Aktiviert |r"
	autoloot.german[3] = "|cFFB0B0B0 Grau (Alles) |r"
	autoloot.german[4] = "|CFFffffff Weiss |r"
	autoloot.german[5] = "|cFF00FF00 Grün |r"
	autoloot.german[6] = "|cFF0000FF Blau |r"
	autoloot.german[7] = "|cFFFF0000 Gegenstand kann nicht gefunden werden |r"
	autoloot.german[8] = "|cFF00FF00 Hinzugefügt: |r"
	autoloot.german[9] = "|cFFFF0000 wurde entfernt |r"
	autoloot.german[10] = " Einträg/e"
	autoloot.german[11] = " Loot-Methode wurde geändert zu "
	autoloot.german[12] = " Lootlog - Blacklist wurde |cFF00FF00 Aktiviert |r"
	autoloot.german[13] = " Lootlog - Blacklist wurde |cFFFF0000 Deaktiviert |r"
	autoloot.german[14] = "Verlauf"
	autoloot.german[15] = "Qualität"
	autoloot.german[16] = "|cFF00FF00 Frei |r"
	autoloot.german[17] = "Dies ist das erste mal, das du Autoloot verwendest"
	autoloot.german[18] = "Autoloot Aktiviert: "
	autoloot.german[19] = "Autoloot Qualität:"
	autoloot.german[20] = "Loot Blacklist:"
	autoloot.german[21] = "Lootlog Blacklist:"
	autoloot.german[22] = "< Blacklist >"
	autoloot.german[23] = "Lootlog Aktiviert: "
	autoloot.german[24] = "Weiter"
	autoloot.german[25] = "Zurück"
	autoloot.german[26] = "Entfernen"
	autoloot.german[27] = "Zurücksetzten"
	autoloot.german[28] = "Nachricht eingeben"
	autoloot.german[29] = "Nicht in Raids"
	autoloot.german[30] = "Sammel - Modus"
	autoloot.german[31] = "Menü öffnen"
	autoloot.german[32] = "Item hinzufügen (Name oder ID)"
	autoloot.german[33] = "Verschieben"
	autoloot.german[34] = "Verlauf Anzeigen"
	autoloot.german[35] = "Nicht in Gruppen"
	autoloot.german[36] = "Qualität ="
	autoloot.german[37] = "Loot-Anzeige"
	autoloot.german[38] = "Entsperrt - Verschiebbar"
	autoloot.german[39] = "|cFFFF0000 Dies ist während eines Kampfes nicht möglich |r"
	autoloot.german[40] = "|cFFFF0000 Der Eintrag enthält keinen Wert |r"
	autoloot.german[41] = "Einblendungsdauer"
	autoloot.german[42] = "Ausblendungsdauer"
	autoloot.german[43] = "Anzeigedauer"
	autoloot.german[44] = "Verlauf löschen"
	autoloot.german[45] = "Nachricht wurde geändert"
	autoloot.german[46] = "Sperren"
	autoloot.german[47] = "Lootlog"
	autoloot.german[48] = "< Lootlog - Blacklist >"
	autoloot.german[49] = "Entsperren"
	autoloot.german[50] = "Verhalten"
	autoloot.german[51] = "|cFFB0B0B0 Grau  : Loote Alles |r"
	autoloot.german[52] = "|cFF0000FF Blau  : Loote <= Blau |r"
	autoloot.german[53] = "|cFF00FF00 Grün  : Loote <= Grün |r"
	autoloot.german[54] = "|CFFffffff Weiss : Loote <= Weiss |r"
	autoloot.german[55] = "Zum Makieren Klicke in die Textbox, STRG + C um zu Kopieren"
	autoloot.german[56] = "Neu"
	autoloot.german[57] = "Alt"
	autoloot.german[58] = "Schriftbreite"
	autoloot.german[59] = "Symbolgröße"
	autoloot.german[60] = "Alles klar!"
	autoloot.german[61] = "|cFFFF0000 Alle Einstellungen wurden auf Standart zurückgesetzt |r"
	autoloot.german[62] = "Zurücksetzten"
	autoloot.german[63] = "Löschen"
	autoloot.german[64] = "Löschen eingeben"
	autoloot.german[65] = "und Enter Drücken"
	autoloot.german[66] = "Jedes mal, wenn du eine Nachricht erhälst, wird der Eingegebene Text zurückgeflüstert"
	autoloot.german[67] = "Min-Preis"
	autoloot.german[68] = "Auto-Roll wurde zu Gier geändert"
	autoloot.german[69] = "Auto-Roll wurde zu Passen geändert"
	autoloot.german[70] = "Auto-Roll wurde zu Entzaubern geändert"
	autoloot.german[71] = "Auto-Roll"
	autoloot.german[72] = "Gegenstand kann nicht entzaubert werden"
	autoloot.german[73] = "Grün wurde Aktiviert"
	autoloot.german[74] = "Blau wurde Aktiviert"
	autoloot.german[75] = "Wenn der Wert kleiner oder gleich -1 beträgt, wird alles Geplündert. Bei Zahlen größer als 0 wird der Preis verglichen und nur geplündert, sollte der des Items größer sein. Der Mindestpreis zum vergleich beträgt 1 Gold."
	autoloot.german[76] = "Mindest-Preis wurde zu "
	autoloot.german[77] = " Gold geändert"
	autoloot.german[78] = "Grün wurde Deaktiviert"
	autoloot.german[79] = "Blau wurde Deaktiviert"
	autoloot.german[80] = "Gier "
	autoloot.german[81] = "Passen "
	autoloot.german[82] = "Entzaubern "
	autoloot.german[83] = "Würfele "
	autoloot.german[84] = " auf "
	autoloot.german[85] = "Auto-Roll"
	autoloot.german[86] = "Invertiert"
	autoloot.german[87] = "Falls du deine Blacklist invertierst, wird nur das Gelootet, was auf der Blacklist steht. Durch Anklicken dieser Option wird dies auf die sich Links befindende Blacklist angewandt"
	autoloot.german[88] = "Zeige auf Loot - Anzeige"
	
	
	
	
	
	
